# 환경 프로필 변경방법
# 오른쪽 위 클릭 후 Edit configuration... 클릭 > Active profiles에 dev, create, deploy 중 하나 입력

spring:
  application:
    name: dongsim
  profiles:
    default: dev # 기본 프로파일: dev
  thymeleaf:
    cache: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL}?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  # hibernate settings
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    show-sql: true

# log4j log level setting
logging.level.kr.ac.jnu.capstone.bigpicture.dongsim: debug

# for JWT
jwt:
  secret: ${JWT_SECRET} # 추후 변경필요
  access:
    expiration: 86400000 # 1일

# for social login
oauth:
  kakao:
    client:
      id: ${KAKAO_CLIENT_ID}
      secret: ${KAKAO_CLIENT_SECRET}